### ISSUE TITLE
adapter model

### ISSUE THREAD

**Issue by bengrol** [bengrol/green-model#3]
Adapter le template avec la charte graphique et logo green

**Comment by Shuunen** [comment]
hésite pas à lister les adaptations attendues, là j'ai commencé par la navbar

**Comment by bengrol** [comment]
### TOUS LES COMPOSANTS

couleurs 
VERT - changer  `#8bc34a` par` #b9d237 / rgb(185, 210, 55)`
VIOLET - adapter css  `.section-content-title -> #573678`


### MODIFS PAR COMPOSANTS 

	Header
About : image de gauche, mettre  [celle ci](https://www.greenisbetter.fr/wp-content/uploads/2017/10/vue5.jpg) - elle vient du site officiel donc on peut l'utiliser.

Pour le texte je m'en occupe.

	Pricing

modifier par Ingredients. Remplacer les tages Breakfast Special Desert Dinner par 

bases - legumes - Fromages - viandes -Fruits - toppings

images dispo sur le site de [commande en ligne](https://www.greenisbetterorder.com/paris8/?compose=114)



Pour la description au survole et le prix sur fond vert, je sais pas trop encore.
Pareil pour le fait que ces elements soient cliquables, je vais voir plus tard.


	Products
Sur le site green, à la page [les-menus-green-is-better](https://www.greenisbetter.fr/les-menus-green-is-better/ ) il y a +/- la même mise en page. On va reprendre les éléments.
Pour les pictos qui sépraent les images du text, je vais me demmerder 

Dans la partie "Menu List" on va afficher les menus Green.

GREEN RUSH 
Base de salades ou de féculents
+ 4 ingrédients au choix
+ sauces au choix

GREEN HOT 
Base de salades ou de féculents
+ 2 ingrédients au choix
+ sauces au choix
+ 1 plat chaud ou wrap ou soupe

GREEN LIFE  
Base de salades ou de féculents
+ 4 ingrédients au choix
+ sauces au choix
+ boisson ou dessert

GREEN LOVE 
Base de salades ou de féculents

- 4 ingrédients au choix
- sauces au choix
- boisson
- dessert

Il va falloir adapter la mise en forme mais je n'ai pas trop d'idée.


	Nav
adapter les liens suites aux modifs

	Reservation
on l'enlève pour le moment

	Contact
pastilles social : laisser facebook et twitter
	
	Map
je n'ai pas encore l'adresse donc pour l'instant on laisse comme ça
	
	Footer
ajouter les Liens suivants (je les ai copié du site green )

```
<a href="http://greenbusinessonly.com/fr/" target="_blank">SITE INTERNATIONAL</a>
<a href="http://www.greenisbetterorder.com/" target="_blank">LIVRAISON A DOMICILE</a>
<a href="http://www.greenbusinessonly.com/fr/greenisbetter-pack_expat/" target="_blank">OUVRIR UN GREEN AUX USA</a>
<a href="https://www.slideshare.net/greensaladbars/fr-gib-brochure-jan2017" target="_blank">BROCHURE FRANCHISE</a>

<div>
	<a href="https://www.youtube.com/channel/UC79WouLYKZ2q_HKO42bEtcw" target="_blank">
<img alt="chaine green is better" src="https://www.greenisbetter.fr/wp-content/uploads/2018/04/yt_logo_rgb_dark.png"> La chaine Green is better</a>
</div>

```
