### ISSUE TITLE
scroll rapide

### ISSUE THREAD

**Issue by bengrol** [bengrol/green-model#4]
Le scroll vertical est très rapide sur mon ordi ainsi que sur mon smarphone.
@Shuunen tu aurais une idée d'ou cela pourrait venir ?

**Comment by Shuunen** [comment]
yes je tente de désactiver un plugin, tu me diras si ça te le fait toujours car je le reproduis ni sur desktop WIn 10 Chrome / Firefox ni sur mon Android

**Comment by bengrol** [comment]
C’ Résolu

Le lun. 20 août 2018 à 03:41, Romain Racamier <notifications@github.com> a
écrit :
